{\rtf1\ansi\ansicpg1252\cocoartf1561\cocoasubrtf600
{\fonttbl\f0\froman\fcharset0 Times-Roman;}
{\colortbl;\red255\green255\blue255;\red70\green70\blue70;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c34510\c34510\c34510;\cssrgb\c0\c0\c0;}
{\*\listtable{\list\listtemplateid1\listhybrid{\listlevel\levelnfc23\levelnfcn23\leveljc0\leveljcn0\levelfollow0\levelstartat0\levelspace360\levelindent0{\*\levelmarker \{none\}.}{\leveltext\leveltemplateid1\'01.;}{\levelnumbers;}\fi-360\li720\lin720 }{\listname ;}\listid1}}
{\*\listoverridetable{\listoverride\listid1\listoverridecount0\ls1}}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\tx220\tx720\pardeftab720\li720\fi-720\sl300\sa240\partightenfactor0
\ls1\ilvl0
\f0\fs26\fsmilli13333 \cf2 \expnd0\expndtw0\kerning0
language\cf3 : \cf2 r \
cache\cf3 : \cf2 packages 
\fs24 \cf3 \uc0\u8232 \
}